"""Subo tablas de la DB

Revision ID: 8ce879a45676
Revises: 
Create Date: 2025-05-22 06:47:59.721654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce879a45676'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rol',
    sa.Column('id_Rol', sa.Integer(), nullable=False),
    sa.Column('nombre_Rol', sa.String(length=50), nullable=True),
    sa.Column('estado_Rol', sa.Boolean(), nullable=True),
    sa.Column('descripcion_Rol', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_Rol')
    )
    op.create_table('habilidades',
    sa.Column('id_Habilidades', sa.Integer(), nullable=False),
    sa.Column('nombre_Habilidades', sa.String(length=50), nullable=True),
    sa.Column('descripcion_Habilidades', sa.String(length=200), nullable=True),
    sa.Column('categoria_Habilidades', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_Habilidades')
    )
    op.create_table('inicio',
    sa.Column('id_Inicio', sa.Integer(), nullable=False),
    sa.Column('nombre_Inicio', sa.String(length=50), nullable=True),
    sa.Column('apellido_Inicio', sa.String(length=50), nullable=True),
    sa.Column('email_Inicio', sa.String(length=60), nullable=True),
    sa.Column('password_Inicio', sa.String(length=100), nullable=True),
    sa.Column('fecha_Creacion', sa.Date(), nullable=True),
    sa.Column('habilidades_Inicio', sa.String(length=200), nullable=True),
    sa.Column('trueques_Inicio', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('descripcion_Inicio', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_Inicio')
    )
    op.create_table('modalidad',
    sa.Column('id_Modalidad', sa.Integer(), nullable=False),
    sa.Column('intercambio_Modalidad', sa.Enum('hibrido', 'presencial', 'virtual'), nullable=True),
    sa.Column('descripcion_Modalidad', sa.String(length=200), nullable=True),
    sa.Column('estado_Modalidad', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_Modalidad')
    )
    op.create_table('registro',
    sa.Column('id_Registro', sa.Integer(), nullable=False),
    sa.Column('nombre_Registro', sa.String(length=50), nullable=True),
    sa.Column('apellido_Registro', sa.String(length=50), nullable=True),
    sa.Column('email_Registro', sa.String(length=60), nullable=True),
    sa.Column('password_Registro', sa.String(length=100), nullable=True),
    sa.Column('fecha_Creacion', sa.Date(), nullable=True),
    sa.Column('habilidades_Registro', sa.String(length=200), nullable=True),
    sa.Column('trueques_Registro', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('descripcion_Registro', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id_Registro')
    )
    op.create_table('usuario',
    sa.Column('id_Usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_Usuario', sa.String(length=50), nullable=True),
    sa.Column('apellido_Usuario', sa.String(length=50), nullable=True),
    sa.Column('email_Usuario', sa.String(length=60), nullable=True),
    sa.Column('password_Usuario', sa.String(length=100), nullable=True),
    sa.Column('fecha_Creacion', sa.Date(), nullable=True),
    sa.Column('habilidades_Usuario', sa.String(length=200), nullable=True),
    sa.Column('trueques_Usuario', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('descripcion_Usuario', sa.String(length=200), nullable=True),
    sa.Column('rol_UsuarioFK', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_UsuarioFK'], ['Rol.id_Rol'], ),
    sa.PrimaryKeyConstraint('id_Usuario')
    )
    op.create_table('curso',
    sa.Column('id_Curso', sa.Integer(), nullable=False),
    sa.Column('nombre_Curso', sa.String(length=50), nullable=True),
    sa.Column('descripcion_Curso', sa.String(length=200), nullable=True),
    sa.Column('fecha_Curso', sa.Date(), nullable=True),
    sa.Column('estado_Curso', sa.Boolean(), nullable=True),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.Column('id_HabilidadesFK', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_HabilidadesFK'], ['habilidades.id_Habilidades'], ),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Curso')
    )
    op.create_table('intercambios',
    sa.Column('id_Intercambios', sa.Integer(), nullable=False),
    sa.Column('fecha_Intercambio', sa.Date(), nullable=True),
    sa.Column('estado_Intercambio', sa.Boolean(), nullable=True),
    sa.Column('descripcion_Intercambio', sa.String(length=200), nullable=True),
    sa.Column('modalidad_Intercambio', sa.Enum(), nullable=True),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.ForeignKeyConstraint(['modalidad_Intercambio'], ['modalidad.id_Modalidad'], ),
    sa.PrimaryKeyConstraint('id_Intercambios')
    )
    op.create_table('notificaciones',
    sa.Column('id_Notificacion', sa.Integer(), nullable=False),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.Column('tipo_Notificacion', sa.Enum('mensaje', 'intercambio', 'valoracion', 'sistema'), nullable=True),
    sa.Column('mensaje_Notificacion', sa.String(length=200), nullable=True),
    sa.Column('leido_Notificacion', sa.Boolean(), nullable=True),
    sa.Column('fecha_Notificacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Notificacion')
    )
    op.create_table('certificaciones',
    sa.Column('id_Certificacion', sa.Integer(), nullable=False),
    sa.Column('nombre_Certificacion', sa.String(length=50), nullable=True),
    sa.Column('descripcion_Certificacion', sa.String(length=200), nullable=True),
    sa.Column('fecha_Certificacion', sa.Date(), nullable=True),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.Column('id_NombreCertificacionFK', sa.Integer(), nullable=True),
    sa.Column('archivo_Certificacion', sa.String(length=200), nullable=True),
    sa.Column('validacion_Certificacion', sa.Boolean(), nullable=True),
    sa.Column('id_UsuarioCertificadorFK', sa.Integer(), nullable=True),
    sa.Column('fecha_Subida', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_NombreCertificacionFK'], ['curso.id_Curso'], ),
    sa.ForeignKeyConstraint(['id_UsuarioCertificadorFK'], ['usuario.id_Usuario'], ),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Certificacion')
    )
    op.create_table('mensaje',
    sa.Column('id_Mensaje', sa.Integer(), nullable=False),
    sa.Column('fecha_Mensaje', sa.Date(), nullable=True),
    sa.Column('descripcion_Mensaje', sa.String(length=200), nullable=True),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.Column('id_IntercambioFK', sa.Integer(), nullable=True),
    sa.Column('leido_Mensaje', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_IntercambioFK'], ['intercambios.id_Intercambios'], ),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Mensaje')
    )
    op.create_table('valoraciones',
    sa.Column('id_Valoracion', sa.Integer(), nullable=False),
    sa.Column('fecha_Valoracion', sa.Date(), nullable=True),
    sa.Column('puntuacion_Valoracion', sa.Float(), nullable=True),
    sa.Column('comentario_Valoracion', sa.String(length=200), nullable=True),
    sa.Column('id_IntercambioFK', sa.Integer(), nullable=True),
    sa.Column('id_UsuarioFK', sa.Integer(), nullable=True),
    sa.Column('id_UsuarioEvaluadorFK', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_IntercambioFK'], ['intercambios.id_Intercambios'], ),
    sa.ForeignKeyConstraint(['id_UsuarioEvaluadorFK'], ['usuario.id_Usuario'], ),
    sa.ForeignKeyConstraint(['id_UsuarioFK'], ['usuario.id_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Valoracion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoraciones')
    op.drop_table('mensaje')
    op.drop_table('certificaciones')
    op.drop_table('notificaciones')
    op.drop_table('intercambios')
    op.drop_table('curso')
    op.drop_table('usuario')
    op.drop_table('registro')
    op.drop_table('modalidad')
    op.drop_table('inicio')
    op.drop_table('habilidades')
    op.drop_table('Rol')
    # ### end Alembic commands ###
