"""Creada tabla categorias

Revision ID: adac45cd4421
Revises: 
Create Date: 2025-05-16 10:25:29.469429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adac45cd4421'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprendiz',
    sa.Column('id_Aprendiz', sa.Integer(), nullable=False),
    sa.Column('nombre_Aprendiz', sa.String(length=50), nullable=True),
    sa.Column('apellido_Aprendiz', sa.String(length=50), nullable=True),
    sa.Column('email_Aprendiz', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_Aprendiz')
    )
    op.create_table('categorias',
    sa.Column('id_Categorias', sa.Integer(), nullable=False),
    sa.Column('descripcion_Categoria', sa.String(length=100), nullable=True),
    sa.Column('nombre_Categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_Categorias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    op.drop_table('aprendiz')
    # ### end Alembic commands ###
