"""Crea tabla experto

Revision ID: b926ce5e52f6
Revises: adac45cd4421
Create Date: 2025-05-16 10:52:20.250775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b926ce5e52f6'
down_revision: Union[str, None] = 'adac45cd4421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experto',
    sa.Column('id_Experto', sa.Integer(), nullable=False),
    sa.Column('nombre_Experto', sa.String(length=50), nullable=True),
    sa.Column('apellido_Experto', sa.String(length=50), nullable=True),
    sa.Column('email_Experto', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_Experto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experto')
    # ### end Alembic commands ###
