"""Crear llave foranea

Revision ID: dbef508b9c36
Revises: c5b3f519fc00
Create Date: 2025-05-16 11:22:51.195393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbef508b9c36'
down_revision: Union[str, None] = 'c5b3f519fc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clase', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.add_column('clase', sa.Column('aprendiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clase', 'aprendiz', ['aprendiz_id'], ['id_Aprendiz'])
    op.create_foreign_key(None, 'clase', 'categorias', ['categoria_id'], ['id_Categorias'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clase', type_='foreignkey')
    op.drop_constraint(None, 'clase', type_='foreignkey')
    op.drop_column('clase', 'aprendiz_id')
    op.drop_column('clase', 'categoria_id')
    # ### end Alembic commands ###
